[package]
name = "mdbook-katex"
version = "0.2.10"
authors = ["Lucas Zanini <zanini.lcs@gmail.com>"]
edition = "2018"
description = "mdBook preprocessor rendering LaTex equations to HTML."
license = "MIT"
readme = "README.md"

[dependencies]
clap = "3.2.14"
mdbook = "0.4.21"
serde_json = "1.0"
